apiVersion: v1
kind: Service
metadata:
  labels:
    app: covid19
  name: covid19
  namespace: covid19-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: covid19
  type: NodePort
